### ISSUE TITLE
opkg segmentation fault on arm7 TomatoUSB

### ISSUE THREAD

**Issue by fedoaa** [davygravy/AirPrint-on-Entware#1]
1. Installed Entware-ng using [this tutorial](https://github.com/Entware-ng/Entware-ng/wiki/Install-on-the-TomatoUSB)
2. Installed some base packages
```
opkg update
opkg install terminfo zlib libjpeg libexpat dbus avahi-daemon file nano htop libbz2 wget
```
3. Downloaded tarball for arm7
```
cd /opt
wget --no-check-certificate https://github.com/davygravy/AirPrint-on-Entware/raw/master/AirPrint-Support-entware-ng-arm7soft.tar.gz
tar xzvf AirPrint-Support-entware-ng-arm7soft.tar.gz
cd AirPrint-Support-entware-ng-arm7soft
```
4. Trying to install any package
```
opkg --force-checksum install cups_2.1.4-2_arm7soft.ipk -t /opt
```
but getting
```
segmentation fault
```
Is there something I'm doing wrong?

**Comment by fedoaa** [comment]
Sorry, my mistake. It's cups_2.1.4-2_arm**v**7soft.ipk not cups_2.1.4-2_arm7soft.ipk
That's why I was getting segmentation fault.

**Comment by davygravy** [comment]
Thank you.  I had missed that, but now it is clear.  Much appreciated, fedoaa.

I should go back and rename the tarball correctly...  armv7 instead of arm7.

If/when I reroll the tarball w/ the newer CUPS and other dependencies, I'll make sure to do that.
