### ISSUE TITLE
通过阅读how to ，完成了安装，但是打印是乱码

### ISSUE THREAD

**Issue by lycugster** [davygravy/AirPrint-on-Entware#2]
环境是tomatousb，Broadcom BCM5357 chip rev 2 pkg 9 ， MIPS 74K V4.9， 硬件是fiberhome 的HG320。用了一个usb hub ，entware ng 安装在u盘， 打印机是 epson L353 墨仓式喷墨打印机。一切安装就绪，运行cups报错，找不到一个libpng，因为新安装的是libpng16，老的cups认得是libpng12，手动改文件名，cups正常启动， 添加打印机正常， 因为没有打印机驱动，是以raw模式安装的，然后在pc（win7 64）上面可以顺利添加共享打印机，正常打印，    ios设备（iPhone ， ipad   均为ios12）可以发现打印机，发送任务，打印的时候却是乱码，错误信息提示， 不支持的格式。好像那个自动配置airprint的页面说了，打印机不能配置raw格式，除非。。。。，      然后我就去epson官网下载了驱动， 不幸的是没有mips平台，只有x86和x86 64
目前是不是已经无解了。

**Comment by lycugster** [comment]
找一台X86 64的pc安装Ubuntu，EPSON官网下载打印机驱动安装，再安装cups等，顺利实现airprint，看来打印乱码还是驱动问题，只有等待gutenprint更新了

**Comment by davygravy** [comment]
So sorry, I can't read Mandarin... :/

**Comment by davygravy** [comment]
OK, I translated your message.  Unfortunately, I cannot build&test on mipselsf because I no longer have a mipselsf router.

I'm guessing that since you may be behind the Great FireWall, you have no access to a translator?

**Comment by lycugster** [comment]
Thank you! I have sovled the problem to use a x86-64 nuc instead the mips router,but in my opinion，use a router as print server is a better choice，router have lower power consume after all. If you want a mips device to test the program , I can donate and post to you. I beg that you can transplant the project to mips device.

**Comment by lycugster** [comment]
Sorry , I am not good at English, but I don't want to use an online translator.

**Comment by davygravy** [comment]
OK, I will try to do this when I return home.   I will roll a tarball (archive) of the same 4 files for mipselsf, and upload it.

You will have to change the "arm7" to "mipselsf" or something like that...

This may be ready by April 21 or so...

**Comment by davygravy** [comment]
By the way, just so you know, the mipselsf-broadcom router's CPU is single core...  It will take it some time to render the pdf/image when you print the "Test Page". 

Also, I don't think there is Chinese/Mandarin localization built into the package... (maybe, maybe not)...

**Comment by davygravy** [comment]
Oh yes, which mipsel are you?  There are two of them in the Entware feed: 
 mipselsf-k3.4/                     OR              mipssf-k3.4/     

??

**Comment by lycugster** [comment]
the router's cpu is BCM5357 ,after login by ssh，I type cat /proc/cpuinfo,then,it output the cpu model is mips 74k v4.9 ,and the router's firmware is tomato usb with linux kernel v2.6,  the entware-ng is mipsel

**Comment by davygravy** [comment]
lycugster, the tarball is now uploaded.  I don't have a router to test this on.  ALSO... important... this is for Entware, not Entware-ng... there may be a compatibilty problem... I don't know.  Also, you may want to inquire here: https://www.linksysinfo.org/index.php?threads/mips-repo-entware-backports-entware-ng-reloaded.74337/

I don't know which better, or even which will work on your router...

**Comment by lycugster** [comment]
Thank U, I'll test on this weekend.

**Comment by davygravy** [comment]
@lycugster , I found the problem and fixed it.   I made a new tarball with airprint support for mipselsf-k2.6, which will work with the old entware-ng feed for opkg/ipkg.

I have tested it on my old router which is Belkin ShareMax N300 running Toastman TomatoUSB...

```
   cat /proc/cpuinfo 
   system type		: Broadcom BCM4716 chip rev 1 pkg 10
   processor		: 0
   cpu model		: MIPS 74K V4.0
   BogoMIPS		: 226.09
   cpu MHz   		: 453


```
And Airprint actually works ... I'll post the tarball with instructions this weekend.

**Comment by davygravy** [comment]
Double-checked.  Works perfectly, cut and paste the commands into the terminal/CLI using my Belkin ShareMax N300 running Toastman TomatoUSB and the older Entware-ng feed here :   http://pkg.entware.net/binaries/mipsel/ .    You could also use it with  maurer's  Entware-backports mentioned here :  https://www.linksysinfo.org/index.php?threads/mips-repo-entware-backports-entware-ng-reloaded.74337/

I'm closing this issue as I've not heard back from you.   Reopen if you find an error, or open an new issue if you are still having no success.
