### ISSUE TITLE
Cups fail with "Filter failed" when printing test page.

### ISSUE THREAD

**Issue by klausrollmann** [davygravy/AirPrint-on-Entware#5]
Hi,

I followed the tutorial with my Linksys e2500v3 mipsel kernel 2.6 router with AdvancedTomato firmware.

I've installed all packages in the 'tar.gz' file you provided here (https://github.com/davygravy/AirPrint-on-Entware/blob/master/airprint-support-mipselsf-k2.6-EntNG.tar.gz). The installation succeeded. The liberation-fonts were not included, so I installed them from entware-ng (http://pkg.entware.net/binaries/mipsel).
In step 12, I tried to print the test page, but after the job is sent to the printer, it shows status 'Stopped - "Filter failed"'

cups, dbus and avahi services are up and running. Cups log is set to "debug", but I couldn't find anything relevant there.

I know that the printer works, because I can setup the printer in my computer using the ip/port 192.168.1.1:9100.

Do you have any idea of what could be the problem?

**Comment by davygravy** [comment]
A few troubleshooting questions:

1)   Which printer (Make and model) do you have connected?   USB?


2)   Have you tried to print with the `lp` command?
-  In the CUPS interface, go Printers>YourPrinter, and then on the Administration Tab, choose : Set as Server Default
-  In a terminal window/CLI,  execute the following:
 

 echo test | lp


It will give you some output about a job and the printer queue…

Report about the output and behavior, along with any messages, verbatim.

3).  Also from the CLI, execute:

opkg list-installed | grep font

Then

opkg list-installed

Post back verbatim output.

Dave

**Comment by klausrollmann** [comment]
1) HP Deskjet 3745 USB
2) If I try to print something with lp, the same thing happens.

root@unknown:/opt# echo test | lp
request id is HP_Deskjet_3740-11 (0 file(s))

If i look at cups the job HP_Deskjet_3740-11 show status: Stopped - "Filter failed";

3)root@unknown:/opt#  opkg list-installed | grep font
fontconfig - 2.12.1-1a
liberation-fonts - 2.00.1-1

For the installed packages I have:
root@unknown:/opt# opkg list-installed
avahi-dbus-daemon - 0.6.32-3
bash - 5.0-2
cups - 2.2.6-3
cups-bsd - 2.2.6-3
cups-client - 2.2.6-3
cups-filters - 1.22.1-2
cups-locales - 2.2.6-3
cups-ppdc - 2.2.6-3
dbus - 1.10.4-1
findutils - 4.6.0-1
fontconfig - 2.12.1-1a
ghostscript - 9.26-2
glib2 - 2.55.0-1
gutenprint - 5.3.1-1
hplip - 3.18.12-1
lcms - 2.9-1
ldconfig - 1.0.17-1
libattr - 20170915-1
libavahi-client - 0.6.32-3
libavahi-dbus-support - 0.6.32-3
libbz2 - 1.0.6-3
libc - 1.0.17-1
libcups - 2.2.6-3
libcupscgi - 2.2.6-3
libcupsimage - 2.2.6-3
libcupsmime - 2.2.6-3
libcupsppdc - 2.2.6-3
libdaemon - 0.14-5
libdb47 - 4.7.25.4.NC-5
libdbus - 1.10.4-1
liberation-fonts - 2.00.1-1
libexpat - 2.2.5-1
libffi - 3.2.1-3
libfreetype - 2.8.1-2
libgcc - 5.4.0-1
libgdbm - 1.11-1
libiconv-full - 1.11.1-3
libidn - 1.33-2
libintl-full - 0.19.8.1-1
libjpeg - 9a-1
libncurses - 6.0-1c
libncursesw - 6.0-1c
libopenssl - 1.0.2n-1
libpcre - 8.41-2
libpng - 1.6.34-1
libpoppler - 0.53.0-1
libpthread - 1.0.17-1
libreadline - 8.0-1
librt - 1.0.17-1
libsqlite3 - 3210000-1
libssp - 5.4.0-1
libstdcpp - 5.4.0-1
libtiff - 4.0.8-1
libusb-1.0 - 1.0.21-1
libusb-compat - 0.1.5-1
libv4l - 0.8.6-2
libxml2 - 2.9.7-1
python - 2.7.14-5
python-base - 2.7.14-5
python-codecs - 2.7.14-5
python-compiler - 2.7.14-5
python-ctypes - 2.7.14-5
python-db - 2.7.14-5
python-decimal - 2.7.14-5
python-distutils - 2.7.14-5
python-email - 2.7.14-5
python-gdbm - 2.7.14-5
python-light - 2.7.14-5
python-logging - 2.7.14-5
python-multiprocessing - 2.7.14-5
python-ncurses - 2.7.14-5
python-openssl - 2.7.14-5
python-pydoc - 2.7.14-5
python-sqlite3 - 2.7.14-5
python-unittest - 2.7.14-5
python-xml - 2.7.14-5
qpdf - 8.4.0-1
sane-libs - 1.0.27-1
terminfo - 6.0-1c
zlib - 1.2.11-1

**Comment by davygravy** [comment]
OK, I have an idea about what this could be...

For your current ipkg feed, are you using :

A.  Alexander's and zyxmon's legacy Entware-ng feed

OR

B.   Maurer's. Entware-backports

OR 

C.  Both

or 

D.  Some other feed?  (if so, please specify)

Here is why I ask.  There were some problems with Ghostscript's support for CUPS in the Entware (Alexander) feed : the CUPS device was missing.

Please try this from the CLI:  

`gs -h | grep cups`  and post back verbatim.



I suspect you may be using a version of Ghostscript that is missing CUPS support.  I noticed that Entware-ng's Ghostscript is 9.16, but I guess that Maurer has followed Alexander's commits and rolled the 9.26, and perhaps the fix for CUPS support hasn't made it into his repo and package feed as of yet. [as an afterthought, I may have included the ghostscript-9.26-2 in the tarball, but according to the directions I posted, I did not install it.  I used the 9.16-1 in the Entware-ng feed.]

There are also some weird interactions between cups-filters and qpdf.   The two in the AirPrint support tarball should play nicely together.

**Comment by klausrollmann** [comment]
I am using  entware-backports(ghostscript 9.26-2). I removed it and installed from entware-ng (ghostscript 9.16-1) and the error is the same.

With ghostscript 9.26-2 installed:
root@unknown:/tmp/home/root# gs -h | grep cups
   chp2200 cif cljet5 cljet5c cljet5pr coslw2p coslwxl cups declj250 deskjet
   /opt/share/cups/fonts/ : /opt/share/fonts/

With ghostscript 9.16-1 installed:
root@unknown:/opt/etc/init.d# gs -h | grep cups
   chp2200 cif cljet5 cljet5c cljet5pr coslw2p coslwxl cp50 cups declj250
   /opt/share/cups/fonts/ : /opt/share/fonts/ : /opt/share/fonts/ubuntu/ :

Did you use entware-ng for the installation? I used entware-backports, maybe I should try to install everything again using entware-ng as the feed?

**Comment by davygravy** [comment]
Both Ghostscripts seem to have the cups device built in. 


Did you restart everything between version changes with /opt/etc/init.d/rc.unslung restart

?

Also, yes I used only entware-ng. 

There are a lot of variables here...

I’d read about someone uninstalling ghostscript from filesystem and files being left on... not everything removed...

To do a pristine install I just used the rc.unslung stop command 

rm  -rf  /opt/*

And then installed it all fresh, starting with entware-ng ...  literally drag and drop the commands from the wikis (Alexander’s old entware-ng wiki and then from mine). 

HTH 

Dave

**Comment by klausrollmann** [comment]
I've removed /opt completely and installed everything from scratch following your tutorial, using entware-ng. There were no installation issues and everything worked. Then I tried to print a test page and the error is still the same: "Filter failed"

One thing I noticed this time is that before showing "Filter failed" in the status, it shows the message "Color Manager: no profiles specified in PPD" for a couple seconds.

Another thin I tried was to manually browse the PPD and select the one I use in my computer (that I know works), but again, the status show "Filter failed"

**Comment by davygravy** [comment]
Klauss,

I've walked through my direction command-by-command, letter-for-letter, drag-and-drop and the only thing I can see that could be an issue is memory (RAM).

The message in your CUPS error log "Filter failed" is so generic-vague-nonspecific that it seems to create more uncertainty than actually pointing a finger in any illuminating direction.  (that's not OUR fault...)

If you have an older MIPSEL router that has say... 64MB ram, it may struggle to get the job done...

What does `free` display for you?


For me, right after installing the package set, before submitting a job, I see this:
```
root@ShareMaxN300:/opt/tmp/airprint-support-mipselsf-k2.6-EntNG# free
             total         used         free       shared      buffers
Mem:         61548        47404        14144            0         1268
-/+ buffers:              46136        15412
Swap:       976368          132       976236
```

After/while submitting a job, I see this:
```
root@ShareMaxN300:/opt/tmp/airprint-support-mipselsf-k2.6-EntNG# free
             total         used         free       shared      buffers
Mem:         61548        52656         8892            0          584
-/+ buffers:              52072         9476
Swap:       976368       100644       875724
```

Running `top` while submitting a job, I see a process that looks like this:
```
 /opt/bin/gs -dQUIET -dPARANOIDSAFER -dNOPAUSE -dBATC
```

The %CPU and %MEM creep up and up... ghostscript is a very processor-intensive applicaition.

This is why I mention two things in the How-To:
1)  Know the limitations of your router/device and its CPU. Don’t expect it to be instantaneous: Broadcom and ARM router CPU’s are not desktop/laptop CPU’s, so know that it might take 15 seconds or more to print an email, for instance. You may have to enable swap space, and it might not work at all, depending on your router’s RAM specs.

and

2)  In the item # 16 Troubleshooting : Prints, but sslllowwwwllly? ... it talks about editing your ppd.  I show how I cut my resolution in 1/4, which by area ( or number of pixels/ dpi) cuts it to 1/16 of the workload for the CPU.   Cutting it in 1/2 would cut the load to 1/4... which would make it faster but not drop the resolution/dpi so much.



The only other think I could see was that you haven't set a hostname (which could be confounding for avahi), but that shouldn't affect CUPS printing.

If it is a RAM/memory exhaustion problem, then there might be a message in the log (dmesg?) or so...

**Comment by klausrollmann** [comment]
It is indeed the RAM. I ran the `free` command and noticed that my swap was 0, so i fixed the swap and then it worked. It took around 3-5 minutes to print the first page, but it worked. Thanks a lot for the help.

**Comment by davygravy** [comment]
Great to hear.  (I was beginning to think there was a problem with one of the packages...  %^\    )  3-5 minutes is way to long.  Altering your `  /opt/etc/cups/ppd/<PRINTERNAME>.ppd`  will cut the print time down to seconds.  IIUC, you can divide the dpi resolutions by any integer as long as your result is an integer.  I've tested it 1/2 and 1/4, but you could experiment with 1/3.

Please let me know if I can close this issue.

Thanks,  Dave

**Comment by klausrollmann** [comment]
The message "Filter failed" was very misleading. I would have never thought that the problem was with the ram. You can close the issue. 
I'll try to reduce the resolution and see if it works.
