### ISSUE TITLE
cups-filters: is poppler completely replaced by qpdf?

### ISSUE THREAD

**Issue by davygravy** [davygravy/AirPrint-on-Entware#6]
https://github.com/OpenPrinting/cups-filters/issues/8  seems to say that qpdf had completely replaced poppler.

Is this correct?

If so, push upstream.

**Comment by tillkamppeter** [comment]
Note that Poppler cannot be replaced by QPDF in general as Poppler is a PDF interpreter and QPDF is not. See my commant [here](https://github.com/OpenPrinting/cups-filters/issues/8#issuecomment-487964108).
But you can build cups-filters without Poppler now as it supports the three PDF interpreters Poppler, Ghostscript, and MuPDF equally. To build a fully functional cups-filters one of the three PDF interpreters is enough.

**Comment by davygravy** [comment]
Thank you @tillkamppeter :  I saw this https://github.com/OpenPrinting/cups-filters/commit/4a1a8e78f92ad031d829b33810c4485bac806efb and figured as much.  

Much appreciated.
